# Generated by Django 3.2.4 on 2022-05-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=50)),
                ('prescripcion', models.CharField(max_length=200)),
                ('fecha_venc', models.CharField(max_length=20)),
            ],
        ),
    ]
