# Generated by Django 3.2.4 on 2022-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('remedio', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=20)),
                ('gramaje', models.CharField(max_length=20)),
                ('caducidad', models.CharField(max_length=20)),
            ],
        ),
    ]
